name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
      - develop

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Set Environment Variables
        run: |
          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
            echo "REACT_APP_ENV=production" >> $GITHUB_ENV
            echo "REACT_APP_CNAME=theonecrawlingsolution.com" >> $GITHUB_ENV
            echo "PUBLISH_BRANCH=gh-pages" >> $GITHUB_ENV
            echo "BUILD_SCRIPT=build:prod" >> $GITHUB_ENV
          else
            echo "REACT_APP_ENV=development" >> $GITHUB_ENV
            echo "REACT_APP_CNAME=develop.theonecrawlingsolution.com" >> $GITHUB_ENV
            echo "PUBLISH_BRANCH=gh-pages-develop" >> $GITHUB_ENV
            echo "BUILD_SCRIPT=build:dev" >> $GITHUB_ENV
          fi

      - name: Build Project
        run: npm run $BUILD_SCRIPT

      - name: Create 404 Fallback
        run: cp build/index.html build/404.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          cname: ${{ env.REACT_APP_CNAME }}
          publish_branch: ${{ env.PUBLISH_BRANCH }}
