name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Set Homepage and CNAME based on branch
        run: |
          BRANCH=$(echo "${{ github.ref }}" | sed 's/refs\/heads\///')
          if [[ "$BRANCH" == "main" ]]; then
            echo "Setting homepage for main branch"
            jq '.homepage="https://theonecrawlingsolution.com"' package.json > temp.json && mv temp.json package.json
            echo "theonecrawlingsolution.com" > public/CNAME
          else
            echo "Setting homepage for develop branch"
            jq '.homepage="https://develop.theonecrawlingsolution.com"' package.json > temp.json && mv temp.json package.json
            echo "develop.theonecrawlingsolution.com" > public/CNAME
          fi

      - name: Build the project
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.DEPLOY_PAT }}
          publish_dir: ./build
          publish_branch: ${{ github.ref == 'refs/heads/main' && 'gh-pages' || 'gh-pages-develop' }}
